// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200119171908_SeedValues")]
    partial class SeedValues
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("Domain.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Name = "Value 101"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Value 102"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Value 103"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Value 104"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Value 105"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
